### PR TITLE
Alex

### PR DESCRIPTION
**Pull request by alexmarcus87**

### CODE REVIEW

**Comment by Alaboudi1** [comment]
Wouldn't it be better if we use Bootstrap icon for help.
http://getbootstrap.com/components/ .

What are you all think?

**Comment by alexmarcus87** [comment]
We liked the Gray text with hover capability that Bootstrap provides better than the glyphs similar to how JSFiddle has it. We can also put the glyph next to the text in the next iteration for sure though.

**Comment by sblake20** [comment]
Check out the Alex and Steph Nav Bar work file included in the pull request. In this one I have the Bootstrap glyph next to the text and have a blue underline on-hover, similar to Js Fiddle as the professor suggested.

**Comment by alexmarcus87** [comment]
Here is an example of the glyphs next to the text:

https://seecoderun-alexmarcus87.c9users.io/index.html#-KAexKhHQweJzmBn6bxx

**Comment by htsungwing** [comment]
I think it's a great feedback to have the header buttons highlights when hover-over. Even nicer the color matches our website logo :)

**Pull request closed without merging**
