### PR TITLE
Merging traceHelper functions to traceSprint2 for Aurelia

### PR DESCRIPTION
**Pull request by htsungwing**

### CODE REVIEW

**Comment by luminaxster** [comment]
Han, what are we committing here? We should not bring the old implementation into the master branch. I saw some documentation in the traceService folder. We can use that. Is there a reason to bring the rest?

**Comment by htsungwing** [comment]
David, a lot of changes are what I pulled from sprintTrace2 awhile back. I don't know what you modified or deleted afterwards, but the only thing I've been making changes to are Jasmine Unit Testing and examples from using the old implementation plus code into traceHelper.js.

**Comment by luminaxster** [comment]
Did you pull before pushing your branch? It seems that is adding the "include" folder. I haven't check the rest.

**Comment by htsungwing** [comment]
Too much junk/old code from old implementation. Closing pull request without merging.

**Comment by luminaxster** [comment]
Han, enter your new stuff , we need them,  into traceSprint2 directly. I just pushed all my changes

**Comment by htsungwing** [comment]
As you wish :)

**Pull request closed without merging**
