### PR TITLE
Issue4

### PR DESCRIPTION
**Pull request by Ashwin060290**
Adding the history slider

### CODE REVIEW

**Comment by luminaxster** [comment]
Ashwin, what errors are you having? could you elaborate on them?
Also, as we discussed, remove all comments =P

**Comment by Ashwin060290** [comment]
no errors - wish to merge it to the master
Professor has asked me to keep the comments so its easy to understand

**Comment by jbhilton11** [comment]
The comments David is referring to are the ones where you commented out code. i.e. Console log statements and such

**Comment by Ashwin060290** [comment]
Removed the commented out code

**Comment by luminaxster** [comment]
Moving the pull request to my branch, I'll debug from there

**Pull request closed without merging**
